### ISSUE TITLE
logrotate の Makefile を書く

### ISSUE THREAD

**Issue by bgpat** [dbgofy/isucon13#12]
```[tasklist]
### Tasks
- [ ] https://github.com/dbgofy/isucon13/issues/6
- [ ] https://github.com/dbgofy/isucon13/issues/7
- [ ] https://github.com/dbgofy/isucon13/issues/8
- [x] Makefile の step 追加
```
